### ISSUE TITLE
Rom restart when entering the Pokedex.

### ISSUE THREAD

**Issue by Inthegrave** [Gamer2020/EmeraldROMBaseGenerator#1]
I start with a clean rom and open Pokemon Emerald in the tool And I leave mostly everything at default 
and have all 3 features checked. setting only number of Pokemon to add to 200 and number of National dex entries to 600 and number of items to add to 0. When starting a new game and getting the Pokedex for the first time and then proceeding to open it causes the game to immediately restart.

**Comment by Gamer2020** [comment]
First, which ROM dump are you using?

**Comment by Inthegrave** [comment]
I don't dump my roms, I buy the original game and then I download the roms from a reputable site.
Is that what you mean? Or do you mean the language? I'm using a USA version.

**Comment by Gamer2020** [comment]
There are many different ROM dumps out there. Even though you are using a USA version it is possible that it is not the right one. Please make sure you are using ROM dump 1986 - Pokemon Emerald (U)(TrashMan).gba

**Comment by Inthegrave** [comment]
I am. I got it from here [https://www.emuparadise.me/Nintendo_Gameboy_Advance_ROMs/Pokemon_Emerald_(U)(TrashMan)/45224](url)

**Comment by Gamer2020** [comment]
Ok, that should be fine. I will have to do some testing this weekend to narrow down the problem. 

Have you tried doing just the Pokemon expansion? Does it work when only it is applied.

**Comment by Inthegrave** [comment]
I will try that.

**Comment by Inthegrave** [comment]
I tried what you said with a clean rom and default values in the base generator I unchecked the other things. this time opening the Pokedex crashes the game. Also just so you, I think this tool uses an outdated version of Dizzy's battle engine.

**Comment by Gamer2020** [comment]
The program pulls the latest versions off of the Github. I'll check it out over the weekend.

**Comment by Gamer2020** [comment]
Had a few minutes. Did just the Pokemon Expansion and the Pokedex works fine.
![alt tag](http://i.imgur.com/CDfdbLS.png)
My next question is, what are you using to run the ROM?

**Comment by Inthegrave** [comment]
Mgba, its supposed to be the most stable Emulator around.

**Comment by Inthegrave** [comment]
Okay an update. I used a fresh rom and I used XSE to expand the rom size to 32mb, next I applied only the Pokemon Expansion and I left the values at default, I started a new game and when I get the Pokedex, the game restarts. I tried this on 3 different emulators, mGBA, VBA and VBA-M. On every single one results in the game restarting.

**Comment by Gamer2020** [comment]
Please try No$gba so I can rule that out. I should be home in a few hours.

**Comment by Inthegrave** [comment]
Tried it, same thing.

**Comment by Gamer2020** [comment]
Only thing left is for me is to assist you through team viewer to see what's going on.

**Comment by Inthegrave** [comment]
Team viewer? What is that?

**Comment by Gamer2020** [comment]
https://www.google.com/#safe=active&q=teamviewer

**Comment by Inthegrave** [comment]
So its sort of like Skype?

**Comment by Gamer2020** [comment]
Kind of. I'll be home in a few hours if you want to get on.

**Comment by Inthegrave** [comment]
I just would have to learn how to use it. I don't think I'm ready for it.

**Comment by Gamer2020** [comment]
It's the only way I could help you that this point and it's pretty straight forward. The Pokedex is working fine for us so there is something going wrong on your end.To only way to identify the problem is to actually be able to see it.

**Comment by Gamer2020** [comment]
Issue closed. Comment if you still need help.

**Comment by Gamer2020** [comment]
Question. What offset is everything being written to?

**Comment by Element420** [comment]
Same problem man, really fucking wierd tbh

**Comment by Element420** [comment]
But see if compiling by hand works for you, no method has worked for me, and this isnt an issie with ERBG , its with dizzyeggs pokemon expansion

**Comment by Gamer2020** [comment]
Do not comment on another person's issue. If the issue is with the Pokémon expansion then please post in the correct place.
